apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmx-spring-boot
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2  # Beperk het aantal oude ReplicaSets tot 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # Houd altijd een pod beschikbaar
      maxSurge: 1        # Sta toe dat er tijdelijk 1 extra pod draait tijdens de update
  selector:
    matchLabels:
      app: htmx-spring-boot
  template:
    metadata:
      labels:
        app: htmx-spring-boot
    spec:
      imagePullSecrets:
        - name: registry-cicdrych
      containers:
        - name: htmx-spring-boot
          image: registry.digitalocean.com/cicdrych/htmx-spring-boot:SHA_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 1010
#          resources:
#            requests:
#              cpu: "100m"
#              memory: "100Mi"
#            limits:
#              cpu: "250m"
#              memory: "500Mi"