apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmx-spring-boot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmx-spring-boot
  template:
    metadata:
      labels:
        app: htmx-spring-boot
    spec:
      imagePullSecrets:
        - name: digitalocean-registry-secret
      containers:
        - name: htmx-spring-boot
          image: registry.digitalocean.com/cicdrych/htmx-spring-boot:SHA_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 1010