apiVersion: v1
kind: Service
metadata:
  name: htmx-spring-boot-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  type: LoadBalancer
  selector:
    app: htmx-spring-boot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1010