name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build en Push naar DigitalOcean Registry
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to DigitalOcean Container Registry
        run: podman login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_USERNAME }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build Docker image with Podman
        run: |
          podman build -t localhost/htmx-spring-boot:1 .

      - name: Tag image for DigitalOcean Container Registry
        run: |
          podman tag localhost/htmx-spring-boot:1 registry.digitalocean.com/cicdrych/htmx-spring-boot:1

      - name: Push Docker image to DigitalOcean Container Registry
        run: |
          podman push registry.digitalocean.com/cicdrych/htmx-spring-boot:1

  # Job 2: Deploy naar Kubernetes
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Zorgt ervoor dat de deploy job alleen draait als de build job slaagt
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Stap 5: Maakt de '.kube' directory aan voor het opslaan van Kubernetes configuratiebestanden
      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      # Stap 6: Zet de KUBECONFIG-variabele in met de waarde uit de geheimen.
      - name: Set KUBECONFIG
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Stap 7: Installeert kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl"  
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Stap 8: Updatet het Kubernetes deployment bestand met de nieuwe Docker image die zojuist is gebouwd
      - name: Update Kubernetes deployment with new image
        run: |
          sed -i "s|image: .*|image: registry.digitalocean.com/cicdrych/htmx-spring-boot:1|g" kubernetes/deployment.yaml

      # Stap 9: Controleert of het bijgewerkte Kubernetes deployment YAML bestand de juiste image bevat
      - name: Check updated deployment YAML
        run: cat kubernetes/deployment.yaml

      # Stap 10: Deployt het bijgewerkte Kubernetes deployment bestand naar het cluster.
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl rollout status deployment/htmx-spring-boot-deployment