name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build en Push naar DigitalOcean Register
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to DigitalOcean Container Registry
        run: |
          echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | podman login registry.digitalocean.com --username ${{ secrets.DIGITALOCEAN_USERNAME }} --password-stdin

      - name: Build Docker image with Podman
        run: |
          podman build -t htmx-spring-boot:1 .

      - name: Tag image for DigitalOcean Container Registry
        run: |
          podman tag localhost/htmx-spring-boot:1 registry.digitalocean.com/cicdrych/htmx-spring-boot:1

      - name: Push Docker image to DigitalOcean Container Registry
        run: |
          set -e
          (podman push registry.digitalocean.com/cicdrych/htmx-spring-boot:1 || {
          echo "Fout: 403 Forbidden. Waarschijnlijk bestaat er al een image met deze tag. Verwijder deze eerst in de Container Registry op DigitalOcean.";
          exit 1; 
          })

  # Job 2: Deploy naar Kubernetes
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Zorgt ervoor dat de deploy job alleen draait als de build job slaagt

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl if not present
        run: |
          if ! command -v doctl &> /dev/null; then
            echo "doctl niet gevonden. Installeren..."
            curl -L https://github.com/digitalocean/doctl/releases/download/v1.87.0/doctl-1.87.0-linux-amd64.tar.gz -o doctl.tar.gz
            tar xzf doctl.tar.gz
            sudo mv doctl /usr/local/bin/
          else
            echo "doctl is al geïnstalleerd. Installatie overslaan."
          fi

      - name: Authenticate doctl
        run: doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create .kube directory
        run: |
          KUBE_DIR=$HOME/.kube
          if [ ! -d "$KUBE_DIR" ]; then
            mkdir -p $KUBE_DIR
          else
            echo "$KUBE_DIR bestaat al"
          fi

      - name: Set KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config | base64 --decode > kubeconfig

      - name: Install kubectl
        run: |
          if ! command -v kubectl &> /dev/null; then
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
          else
            echo "kubectl is al geïnstalleerd"
          fi

      - name: update image
        run: |
          IMAGE_NAME=registry.digitalocean.com/cicdrych/htmx-spring-boot:1          
          sed -i "s|image: .*|image: $IMAGE_NAME|g" kubernetes/deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
#          kubectl rollout status deployment/htmx-spring-boot